### ISSUE TITLE
Add Array.insert

### ISSUE THREAD

**Issue by AlienKevin** [elm-community/array-extra#19]
Insert an element to an array at a specific index (can be negative).

```elm
insert : Int -> a -> Array a -> Array a
insert i el arr =
  Array.append
  ( Array.push el <|
    Array.slice 0 i arr
  )
  (Array.slice i (Array.length arr) arr)
```

Check out sample tests on [Ellie](https://ellie-app.com/8Z5D54pVpp7a1)

**Comment by AlienKevin** [comment]
I saw the `insertAt` pull request so I'm closing this issue. Could someone publish the new version with `insertAt` though?

**Comment by jonboiser** [comment]
@prikhi Would you be able to create a new release with this feature?

**Comment by prikhi** [comment]
Sure, happy to help.

**Comment by prikhi** [comment]
New release pushed.
