### ISSUE TITLE
Bug with resizerRepeat

### ISSUE THREAD

**Issue by sindikat** [elm-community/array-extra#3]
Try this code

```
import Graphics.Element exposing (show)
import Array exposing (Array)
import Array.Extra

a = Array.fromList [0..9]

x = Array.Extra.resizelRepeat 3 500 a
y = Array.Extra.resizelRepeat 12 750 a
z = Array.Extra.resizerRepeat 3 1000 a

main = show <| z
```

`z` equals `[9,750,750]`. Now run the following code:

```
import Graphics.Element exposing (show)
import Array exposing (Array)
import Array.Extra

a = Array.fromList [0..9]

-- x = Array.Extra.resizelRepeat 3 500 a
-- y = Array.Extra.resizelRepeat 12 750 a
z = Array.Extra.resizerRepeat 3 1000 a

main = show <| z
```

`z` equals `[7,8,9]`.

Apparently, something going on with an array on the JavaScript side. This bug most likely has to do with upstream, but I am not sure at all how to narrow this bug down yet.

All I know it has to do with `Array.repeat` or `Array.append`, because this bug happens only when the code

```
xs `append` repeat (n - l) val
```

is activated inside `resizelRepeat` body ([code line](https://github.com/circuithub/elm-array-extra/blob/1.0.2/src/Array/Extra.elm#L140)).

**Comment by rehno-lindeque** [comment]
Thanks for pointing this out in core - I basically stopped using Array because it seemed buggy and I could imagine hunting down the problem for days. It's nice to see a test case. 

Seems like something that needs to be fixed upstream? We can retest once the linked issue is fixed.

**Comment by prikhi** [comment]
Seems fixed: https://ellie-app.com/4StfZgLbPTYa1
