### ISSUE TITLE
Drop elm- from package name

### ISSUE THREAD

**Issue by jvoigtlaender** [elm-community/array-extra#7]
As per this: https://github.com/elm-community/Manifesto/issues/27.

**Comment by jvoigtlaender** [comment]
@jonboiser, if you are ready to do this, let me know. Probably you do not have the access rights to change the repository name on GitHub itself. But I do. Adapting the `elm-package.json` file, removing old release tags, etc., you should be able to do yourself as maintainer.

**Comment by jonboiser** [comment]
@jvoigtlaender I don't think I've been added to the elm-community org yet or given access to this repo. Does @rgrempel need onboard me?

But please go ahead and make the updates so all the libraries are consistent.

**Comment by jvoigtlaender** [comment]
I've given you write access to `elm-array-extra` and `elm-list-split`, and renamed both repositories by dropping `elm-`.

**Comment by jonboiser** [comment]
Cool, thanks!
